### ISSUE TITLE
不存在文件dbCountPswSolsticeALDDD.txt 并且不存在数据库SQL文件

### ISSUE THREAD

**Issue by 838728713** [anjoy8/ChristDDD#5]
请大佬提供一份SQL数据库文件

**Comment by anjoy8** [comment]
1、dbCountPswSolsticeALDDD.txt 文件就是数据库连接字符串 server=123.206.xx.xxx;uid=sa;pwd=123456;database=Christ

2、数据库文件，这是用EFCore写的，你直接通过 CodeFirst 就可以生成数据库了。

**Comment by 838728713** [comment]
谢谢哈,昨天已经注意到是codefirst了   没用过这个 so 不是很清楚  麻烦了.感谢的你的回答
